
INSERT INTO article (NAME) VALUES ('name1');
INSERT INTO trek (NAME, YEAR, LOCATION) VALUES ('name1', '2019', 'LOCATION1'); 
INSERT INTO day (NUMBER, TREK_ID) VALUES ('NUMBER1', 1); 

INSERT INTO article (NAME) VALUES ('name2');
INSERT INTO trek (NAME, YEAR, LOCATION) VALUES ('name2', '2019', 'LOCATION2'); 
INSERT INTO day (NUMBER, TREK_ID) VALUES ('NUMBER2', 2); 
